### ISSUE TITLE
FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsucces

### ISSUE THREAD

**Issue by shoaibz90** [tuminoid/gitlab-installer#11]
getting below error while bootstrapping a node.

Creating new client for <nodename>
Creating new node for <nodename>
Connecting to xxxx
xxx -----> Existing Chef installation detected
xxx Starting the first Chef Client run...
xx Starting Chef Client, version 11.10.4
xxx resolving cookbooks for run list: []
xxx Synchronizing Cookbooks:
xxx Compiling Cookbooks...
xxx [2017-01-18T11:31:25-05:00] WARN: Node myapps-drp-dev has an empty run list.
xxx Converging 0 resources

xxxx Running handlers:
xxxx [2017-01-18T11:31:25-05:00] ERROR: Running exception handlers
xxxx Running handlers complete
xxxx
xxxx [2017-01-18T11:31:25-05:00] ERROR: Exception handlers complete
xxxx [2017-01-18T11:31:25-05:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
xxxx Chef Client failed. 0 resources updated in 2.889895 seconds
xxxx [2017-01-18T11:31:26-05:00] ERROR: "\xC3" on US-ASCII
xxxx [2017-01-18T11:31:26-05:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsucces
sfully (exit code 1)

**Comment by tuminoid** [comment]
`xxxx [2017-01-18T11:31:26-05:00] ERROR: "\xC3" on US-ASCII` would look like a invisible non-space space in probably `gitlab.rb`, and it causes Chef to fail due syntax error.
