### ISSUE TITLE
Testers needed for Parallels and Vmware Fusion Prior to putting pull request

### ISSUE THREAD

**Issue by agiletechnologist** [tuminoid/gitlab-installer#16]
I have created a modification using the vagrant box "bento/ubuntu-16.04" which supports virtualbox, vmware (fusion and workstation) and parallels providers.  (see https://github.com/agiletechnologist/gitlab-installer to clone for testing). I  have tested 2 of 6 tested. LXC did not change.  

### Changes

- Vagrantfile - Changed default box to "bento/ubuntu-16.04"
- Vagrantfile - Changed  vmware_fusion to be vmware_desktop which will work with both vmware_fusion and vmware_workstation providers and removed override of the box for vmware_desktop
- Vagrantfile - fixed default for GITLAB_CPUS to match Documentation default of 2 
- README.md - for new minimum  memory default for GITLAB_MEMORY of 3072
- install-gitlab.sh - Added apt-get upgrade before installation to apply updates and security updates before installing.

Providers checked:

- [x] virtualbox on Windows (Completed)

- [x] virtualbox Linux

- [x] virtualbox Mac

- [x] vmware_workstation  Windows (Completed)

- [ ] vmware_workstation Linux

- [ ] vmware_fusion Mac

- [x] Parallels Mac

- [ ] LXC Linux Containers 

Thanks for any help.

**Comment by tuminoid** [comment]
Hello @agiletechnologist! I took a sneak peek into your fork and changes, and it looks very good!  I will test both Mac and Linux Virtualbox providers and Mac Parallels provider later this week.

LXC support I wouldn't consider necessary. LXC is quickly becoming/became obsolete with LXD and Docker gaining support. Also even partial VMware support is better than no support. I'd encourage you to send pull request already.

**Comment by agiletechnologist** [comment]
@tuminoid The Pull request is created #17

**Comment by agiletechnologist** [comment]
Tested virtualbox Linux on ubuntu should work on other distros as the host.

**Comment by tuminoid** [comment]
I've tested the Mac Parallels and Virtualbox 5.2, and found no issues.

As commented above, this is improvement even with LXC and VMWare/Mac being untested, and I will merge the pull request now. Thank you for the contribution!
