### ISSUE TITLE
Dear Tuminoid, this is more of a question...

### ISSUE THREAD

**Issue by jendxb** [tuminoid/gitlab-installer#21]
your project runs without problems

But I cannot reach either of the the links you provide.
What am I doing wrong?

jennifer

**Comment by tuminoid** [comment]
Hello Jennifer, what exact links do you mean?

**Comment by jendxb** [comment]
Dear Tuomo,
thank you for getting back to me.

On your README file, in the usage section you have 2 links:
- https://172.0.0.1:8443
- https://127.0.0.1

I have no luck executing these links.

Greetings from Berlin 
Jennifer

**Comment by tuminoid** [comment]
I've just verified that https://127.0.0.1:8443 works after `vagrant up`. You just need to accept self-signed certificate in your browser to access the UI.

Could you list the steps you have executed? Is VM provisioning completing successfully?

**Comment by jendxb** [comment]
Dear Tuomo,

 

my problem is that the project runs to the and then simply finishes with a login prompt. takes about 6 minutes on my Mac.

 

How and when would I add the self-signed cert?

 

Sunday greetings from Berlin

Jennifer

**Comment by tuminoid** [comment]
Jen, all you need to do is:
- `vagrant up`: this brings up the VM with Gitlab installed
- open your browser, and navigate to https://127.0.0.1:8443 and in browser accept the security warning about self-signed certificate
- enjoy GitLab

**Comment by jendxb** [comment]
Dear Tuomo,

thank you for your help!
— Jen

**Comment by tuminoid** [comment]
I believe this is solved. Closing.

**Comment by jendxb** [comment]
… yes.

 

Thank you again.

 

Sunny greetings from Berlin.

-- Jennifer
