### ISSUE TITLE
(GitLab 8.0.1-ce.1) Error executing action `create` on resource 'template[/var/opt/gitlab/nginx/conf/gitlab-ci-http.conf]'

### ISSUE THREAD

**Issue by joseph-onsip** [tuminoid/gitlab-installer#4]
Thanks for all your work on this! It's come in very handy for trying out GitLab without much hassle. I think this issue might be more related to GitLab than to this installer, but I wanted to make sure you were aware of it.

I tried to install GitLab 8 using this, but there were a variety of errors, the first of which is in the issue title. I copied `gitlab.rb.example` to `gitlab.rb` and ran `vagrant up`. Here's a link to the console log showing the first error encountered: https://gist.github.com/joseph-onsip/8c1fada84998b8b9e7b5#file-gistfile1-txt-L807

I tried simply creating the directory (`mkdir -p /var/opt/gitlab/nginx/conf`) and reprovisioning (`vagrant provision`), which appeared to complete successfully, but visiting `https://127.0.0.1:8443` gives a 500 response:

```
500

Whoops, something went wrong on our end.

Try refreshing the page, or going back and attempting the action again.

Please contact your GitLab administrator if this problem persists.
```

I *did* try going back to the `bento/ubuntu-14.04` basebox from #3, but experienced the same error, so I don't think this is related to the switch to `ubuntu/trusty64`.

Finally, pinning to GitLab 7.14.3-ce.1 works for me: https://gist.github.com/joseph-onsip/a92b4fe5d5cc2d34d4c3

I'll probably keep investigating, as I'm eager to get this working with GitLab 8. Thanks again!

**Comment by tuminoid** [comment]
Thank you for reporting!

In Gitlab 8, they have included CI as part of the main package. CI related options in `gitlab.rb` cause Chef to panic, so you need to remove or comment them out:
```
# ci_external_url 'http://gitlabci.invalid/'
# nginx['redirect_http_to_https'] = false
```

This is fixed in `gitlab.rb.example` at commit 75c0a8312f933706463a3356d984d8545118e94a.

**Comment by joseph-onsip** [comment]
Ah, I should have looked a little closer and guessed that was happening. Cheers for the quick fix!
