### ISSUE TITLE
GnuTLS recv error (-9)

### ISSUE THREAD

**Issue by od3n** [tuminoid/gitlab-installer#6]
Failed to fetch https://packages.gitlab.com/gitlab/gitlab-ce/ubuntu/pool/trusty/main/g/gitlab-ce/gitlab-ce_8.1.0-ce.1_amd64.deb  GnuTLS recv error (-9): A TLS packet with unexpected length was received.

**Comment by tuminoid** [comment]
Hi,

Thank you for reporting!

This error is happening when network connection is reset, either on your side or the package repository provided by Gitlab. Nothing I can do. Please just recreate the box.
