### ISSUE TITLE
Backup data

### ISSUE THREAD

**Issue by mitchellknight** [tuminoid/gitlab-installer#8]
I was wondering if you had a recommended method for backups? The docs I've found online say I should SSH into the vagrant box and use `sudo gitlab-rake gitlab:backup:create` (GitLab with the Omnibus package) or `sudo -u git -H bundle exec rake gitlab:backup:create RAILS_ENV=production` (GitLab from source). Is there an easier way? Does the vagrant box has a synced folder on the guest machine?

It would be nice if this project could create backups regularly in a Vagrant synced folder.

**Comment by tuminoid** [comment]
It has the default `/vagrant` shared folder. As you already know how to do a backup (the omnibus way), nothing prevents you from setting up a cronjob that executes the backup, and then copies the resulting tarball to say `/vagrant/backups`.

**Comment by mitchellknight** [comment]
Great, I'll try that! Thank you for the suggestion.
