### ISSUE TITLE
Gitlab install issue

### ISSUE THREAD

**Issue by GForceWeb** [tuminoid/gitlab-installer#9]
Kept getting the following error when gitlab was being installed:

`E: Failed to fetch https://packages.gitlab.com/gitlab/gitlab-ce/ubuntu/pool/trusty/main/g/gitlab-ce/gitlab-ce_7.13.2-ce.0_amd64.deb  Hash Sum mismatch`

Following the advice on the [gitlab forums](https://gitlab.com/gitlab-org/omnibus-gitlab/issues/628) I ran the installer manually in the VM using the following command which worked:

apt-get -o 'Acquire::PDiffs="false"' install gitlab-ce

Not sure whether it was something local to my setup or if this is happening to others.

**Comment by tuminoid** [comment]
Hi @GForceWeb, thanks for the report!

Having never experienced this failure myself and but reading thru the provided link, I think I will apply this Pdiff fix to apt config, and probably even add a fallback to downloading manually with curl and then dpkg'ing it in, just to be more reliable, even for slow connection users.

**Comment by tuminoid** [comment]
Fixed with b24cf60fcdf3eed1ef7b8722f77737a3773d8665.
